import { PrismaClient, PlanCode } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // Demo user — for local development only
  // Password: "password123" (Argon2id hash generated by the API on first run)
  // Use POST /api/v1/auth/register in dev to create real users
  console.log("Seed complete. Register via API to create real users.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
