/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppReadingListRouteImport } from './routes/_app.reading-list'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppArchiveRouteImport } from './routes/_app.archive'
import { Route as AppTopicsIndexRouteImport } from './routes/_app.topics.index'
import { Route as AppBookshelvesIndexRouteImport } from './routes/_app.bookshelves.index'
import { Route as AppTopicsSlugRouteImport } from './routes/_app.topics.$slug'
import { Route as AppReadItemIdRouteImport } from './routes/_app.read.$itemId'
import { Route as AppBookshelvesSlugRouteImport } from './routes/_app.bookshelves.$slug'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppReadingListRoute = AppReadingListRouteImport.update({
  id: '/reading-list',
  path: '/reading-list',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsIndexRoute = AppTopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookshelvesIndexRoute = AppBookshelvesIndexRouteImport.update({
  id: '/bookshelves/',
  path: '/bookshelves/',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsSlugRoute = AppTopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppReadItemIdRoute = AppReadItemIdRouteImport.update({
  id: '/read/$itemId',
  path: '/read/$itemId',
  getParentRoute: () => AppRoute,
} as any)
const AppBookshelvesSlugRoute = AppBookshelvesSlugRouteImport.update({
  id: '/bookshelves/$slug',
  path: '/bookshelves/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/extension': typeof ExtensionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/archive': typeof AppArchiveRoute
  '/inbox': typeof AppInboxRoute
  '/library': typeof AppLibraryRoute
  '/plan': typeof AppPlanRoute
  '/reading-list': typeof AppReadingListRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/bookshelves/$slug': typeof AppBookshelvesSlugRoute
  '/read/$itemId': typeof AppReadItemIdRoute
  '/topics/$slug': typeof AppTopicsSlugRoute
  '/bookshelves/': typeof AppBookshelvesIndexRoute
  '/topics/': typeof AppTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/extension': typeof ExtensionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/archive': typeof AppArchiveRoute
  '/inbox': typeof AppInboxRoute
  '/library': typeof AppLibraryRoute
  '/plan': typeof AppPlanRoute
  '/reading-list': typeof AppReadingListRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/bookshelves/$slug': typeof AppBookshelvesSlugRoute
  '/read/$itemId': typeof AppReadItemIdRoute
  '/topics/$slug': typeof AppTopicsSlugRoute
  '/bookshelves': typeof AppBookshelvesIndexRoute
  '/topics': typeof AppTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/extension': typeof ExtensionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/archive': typeof AppArchiveRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/reading-list': typeof AppReadingListRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/bookshelves/$slug': typeof AppBookshelvesSlugRoute
  '/_app/read/$itemId': typeof AppReadItemIdRoute
  '/_app/topics/$slug': typeof AppTopicsSlugRoute
  '/_app/bookshelves/': typeof AppBookshelvesIndexRoute
  '/_app/topics/': typeof AppTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/extension'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/archive'
    | '/inbox'
    | '/library'
    | '/plan'
    | '/reading-list'
    | '/search'
    | '/settings'
    | '/bookshelves/$slug'
    | '/read/$itemId'
    | '/topics/$slug'
    | '/bookshelves/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/extension'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/archive'
    | '/inbox'
    | '/library'
    | '/plan'
    | '/reading-list'
    | '/search'
    | '/settings'
    | '/bookshelves/$slug'
    | '/read/$itemId'
    | '/topics/$slug'
    | '/bookshelves'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/design-system'
    | '/extension'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_app/archive'
    | '/_app/inbox'
    | '/_app/library'
    | '/_app/plan'
    | '/_app/reading-list'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/bookshelves/$slug'
    | '/_app/read/$itemId'
    | '/_app/topics/$slug'
    | '/_app/bookshelves/'
    | '/_app/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  ExtensionRoute: typeof ExtensionRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reading-list': {
      id: '/_app/reading-list'
      path: '/reading-list'
      fullPath: '/reading-list'
      preLoaderRoute: typeof AppReadingListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archive': {
      id: '/_app/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topics/': {
      id: '/_app/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof AppTopicsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookshelves/': {
      id: '/_app/bookshelves/'
      path: '/bookshelves'
      fullPath: '/bookshelves/'
      preLoaderRoute: typeof AppBookshelvesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topics/$slug': {
      id: '/_app/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof AppTopicsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/read/$itemId': {
      id: '/_app/read/$itemId'
      path: '/read/$itemId'
      fullPath: '/read/$itemId'
      preLoaderRoute: typeof AppReadItemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookshelves/$slug': {
      id: '/_app/bookshelves/$slug'
      path: '/bookshelves/$slug'
      fullPath: '/bookshelves/$slug'
      preLoaderRoute: typeof AppBookshelvesSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArchiveRoute: typeof AppArchiveRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppPlanRoute: typeof AppPlanRoute
  AppReadingListRoute: typeof AppReadingListRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppBookshelvesSlugRoute: typeof AppBookshelvesSlugRoute
  AppReadItemIdRoute: typeof AppReadItemIdRoute
  AppTopicsSlugRoute: typeof AppTopicsSlugRoute
  AppBookshelvesIndexRoute: typeof AppBookshelvesIndexRoute
  AppTopicsIndexRoute: typeof AppTopicsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchiveRoute: AppArchiveRoute,
  AppInboxRoute: AppInboxRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppPlanRoute: AppPlanRoute,
  AppReadingListRoute: AppReadingListRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppBookshelvesSlugRoute: AppBookshelvesSlugRoute,
  AppReadItemIdRoute: AppReadItemIdRoute,
  AppTopicsSlugRoute: AppTopicsSlugRoute,
  AppBookshelvesIndexRoute: AppBookshelvesIndexRoute,
  AppTopicsIndexRoute: AppTopicsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  ExtensionRoute: ExtensionRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
